In [1]:
!pip install sqlalchemy pandas pymysql
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\user\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pandas in c:\users\user\appdata\roaming\python\python313\site-packages (3.0.2)
Requirement already satisfied: pymysql in c:\users\user\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sqlalchemy in c:\users\user\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [2]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

engine = create_engine("mysql+pymysql://root:root123@localhost/hospital_project")

In [3]:
import os
os.listdir("C:/Users/user/Downloads/hospital_datasets")

['admissions_raw.csv',
 'billing_claims_raw.csv',
 'departments.csv',
 'doctors.csv',
 'followups_raw.csv',
 'hospitals.csv',
 'lab_results_raw.csv',
 'patients_raw.csv',
 'pharmacy_orders_raw.csv',
 'treatments_raw.csv']

In [4]:
from sqlalchemy import create_engine
import pandas as pd
import os
import mysql.connector

# MySQL URI format
# URL-encoded password
# Original password: Rp@2121994 → Encoded: Rp%402121994
engine = create_engine("mysql+pymysql://root:root123@localhost/hospital_project")

#  Path to the dataset files

DATA_PATH = "C:/Users/user/Downloads/hospital_datasets"


#  MySQL connector config
config = {
    'user': 'root',
    'password': 'root123',   # Raw password is fine here
    'host': 'localhost',
    'database': 'hospital_project',
    'raise_on_warnings': True
}

#  Connect and insert
try:
    conn = mysql.connector.connect(**config)
    cursor = conn.cursor()
    print(" MySQL connection established successfully.")

    csv_files = [
        'admissions_raw.csv', 
        'billing_claims_raw.csv', 
        'departments.csv', 
        'doctors.csv', 
        'followups_raw.csv', 
        'hospitals.csv', 
        'lab_results_raw.csv', 
        'patients_raw.csv', 
        'pharmacy_orders_raw.csv', 
        'treatments_raw.csv'
    ]

    for file in csv_files:
        df = pd.read_csv(os.path.join(DATA_PATH, file))
        table_name = file.replace('.csv', '').replace('_raw', '')
        df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)
        print(f" Table '{table_name}' created successfully.")

except mysql.connector.Error as err:
    print(f" Error: {err}")
finally:
    if conn.is_connected():
        cursor.close()
        conn.close()
        print(" MySQL connection closed.")

 MySQL connection established successfully.
 Table 'admissions' created successfully.
 Table 'billing_claims' created successfully.
 Table 'departments' created successfully.
 Table 'doctors' created successfully.
 Table 'followups' created successfully.
 Table 'hospitals' created successfully.
 Table 'lab_results' created successfully.
 Table 'patients' created successfully.
 Table 'pharmacy_orders' created successfully.
 Table 'treatments' created successfully.
 MySQL connection closed.

In [5]:
patients = pd.read_sql('SELECT * FROM patients;', engine)
admissions = pd.read_sql('SELECT * FROM admissions;', engine)
treatments = pd.read_sql('SELECT * FROM treatments;', engine)
billing = pd.read_sql('SELECT * FROM billing_claims;', engine)
pharmacy = pd.read_sql('SELECT * FROM pharmacy_orders;', engine)
labs = pd.read_sql('SELECT * FROM lab_results;', engine)
followups = pd.read_sql('SELECT * FROM followups;', engine)
doctors = pd.read_sql('SELECT * FROM doctors;', engine)
departments = pd.read_sql('SELECT * FROM departments;', engine)
hospitals = pd.read_sql('SELECT * FROM hospitals;', engine)





print('patients:', patients.shape)
print('admissions:', admissions.shape)
print('treatments:', treatments.shape)
print('billing:', billing.shape)
print('pharmacy:', pharmacy.shape)
print('labs:', labs.shape)
print('followups:', followups.shape)
print('doctors',doctors.shape)
print('departments:', departments.shape)
print('hospitals:',hospitals.shape)

patients: (12090, 10)
admissions: (30130, 12)
treatments: (90160, 7)
billing: (30080, 10)
pharmacy: (70090, 8)
labs: (60000, 7)
followups: (30000, 7)
doctors (260, 7)
departments: (12, 3)
hospitals: (8, 6)

In [6]:
print(patients.columns)
print(admissions.columns)
print(treatments.columns)
print(billing.columns)
print(pharmacy.columns)
print(labs.columns)
print(followups.columns)
print(doctors.columns)
print(departments.columns)
print(hospitals.columns)

Index(['patient_id', 'patient_code', 'patient_name', 'age', 'gender', 'city',
       'primary_chronic_condition', 'insurance_plan', 'income_segment',
       'registration_date'],
      dtype='str')
Index(['admission_id', 'patient_id', 'hospital_id', 'department_id',
       'primary_doctor_id', 'admission_date', 'discharge_date',
       'admission_type', 'diagnosis', 'severity_level', 'discharge_status',
       'readmitted_30_days'],
      dtype='str')
Index(['treatment_id', 'admission_id', 'doctor_id', 'treatment_type',
       'treatment_cost', 'treatment_date', 'treatment_status'],
      dtype='str')
Index(['bill_id', 'admission_id', 'patient_id', 'payer_type', 'gross_amount',
       'discount_amount', 'insurance_paid', 'patient_paid', 'claim_status',
       'bill_date'],
      dtype='str')
Index(['order_id', 'admission_id', 'patient_id', 'medicine_name', 'quantity',
       'unit_price', 'line_amount', 'pharmacy_type'],
      dtype='str')
Index(['lab_id', 'admission_id', 'patient_id', 'test_name', 'test_value',
       'test_date', 'result_flag'],
      dtype='str')
Index(['followup_id', 'admission_id', 'patient_id', 'followup_due_date',
       'followup_completed', 'followup_mode', 'followup_outcome'],
      dtype='str')
Index(['doctor_id', 'doctor_name', 'department_id', 'specialization',
       'hospital_id', 'experience_years', 'doctor_grade'],
      dtype='str')
Index(['department_id', 'department_name', 'care_complexity'], dtype='str')
Index(['hospital_id', 'hospital_name', 'city', 'ownership_type',
       'bed_capacity', 'launch_year'],
      dtype='str')

In [7]:
patients.head()

,patient_id,patient_code,patient_name,age,gender,city,primary_chronic_condition,insurance_plan,income_segment,registration_date
0,1,P00001,Patient_BKOKF,46.0,Female,Hyderabad,Heart Failure,Premium Insurance,Low,2016-09-25
1,2,P00002,Patient_KXPSW,58.0,Male,Hyderabad,Heart Failure,Basic Insurance,Low,2022-09-12
2,3,P00003,Patient_TJAJT,51.0,Female,Ahmedabad,Hypertension,Government Scheme,Middle,2014-08-02
3,4,P00004,Patient_WYKTO,25.0,Male,NaN,Heart Failure,Self Pay,Middle,2017-03-23
4,5,P00005,Patient_PFFLA,54.0,Male,NaN,Asthma,Basic Insurance,Middle,2021-11-22

In [8]:
admissions.head()

,admission_id,patient_id,hospital_id,department_id,primary_doctor_id,admission_date,discharge_date,admission_type,diagnosis,severity_level,discharge_status,readmitted_30_days
0,1,3415,8,4,123,2024-03-10,2024-03-16,Emergency,Anemia,Critical,Home,Yes
1,2,3610,8,1,209,2023-05-19,2023-05-20,Planned,Arrhythmia,Moderate,Home,No
2,3,7584,8,3,190,2025-06-16,2025-06-18,Emergency,Joint Replacement,Moderate,Home,Yes
3,4,4459,2,3,176,2025-10-15,2025-10-16,Referral,Joint Replacement,Moderate,Home,No
4,5,5508,3,12,140,2024-05-07,2024-05-23,Planned,Multi Organ Dysfunction,Moderate,Home,No

In [9]:
treatments.head()

,treatment_id,admission_id,doctor_id,treatment_type,treatment_cost,treatment_date,treatment_status
0,1,27337,62,Surgery,52636.30,2023-01-01,Completed
1,2,982,242,Imaging,7478.12,2023-01-01,Completed
2,3,17082,238,Chemotherapy,27451.58,2023-01-01,Completed
3,4,4096,1,Lab Package,3379.43,2023-01-01,Pending
4,5,26108,227,ICU Care,19993.51,2023-01-01,Completed

In [10]:
billing.head()

,bill_id,admission_id,patient_id,payer_type,gross_amount,discount_amount,insurance_paid,patient_paid,claim_status,bill_date
0,1,1,3415,Premium Insurance,19940.46,1785.84,15939.06,2215.56,Paid,2024-03-10
1,2,2,3610,Basic Insurance,19034.64,558.14,13981.49,4495.01,Partial,2023-05-19
2,3,3,7584,Self Pay,20965.03,2413.86,18595.28,0.00,Rejected,2025-06-16
3,4,4,4459,Corporate Insurance,16637.20,1938.84,13657.64,1040.72,Rejected,2025-10-15
4,5,5,5508,Government Scheme,77727.52,2213.24,35959.21,39555.07,Paid,2024-05-07

In [11]:
pharmacy.head()

,order_id,admission_id,patient_id,medicine_name,quantity,unit_price,line_amount,pharmacy_type
0,1,29377,7899,Insulin,15,57.66,864.90,IP Pharmacy
1,2,25956,2404,Anticoagulant,1,33.52,33.52,IP Pharmacy
2,3,18883,6450,Chemotherapy Drug,17,188.65,3207.07,OP Pharmacy
3,4,21967,10792,Metformin,3,37.73,113.18,OP Pharmacy
4,5,17705,4645,Amlodipine,20,95.68,1913.64,OP Pharmacy

In [12]:
labs.head()

,lab_id,admission_id,patient_id,test_name,test_value,test_date,result_flag
0,1,2133,11981,CRP,5.99,2023-01-01,Abnormal
1,2,5569,5064,Sodium,2.46,2023-01-01,Normal
2,3,17271,1824,CRP,2.84,2023-01-01,Abnormal
3,4,24486,9939,HbA1c,14.91,2023-01-01,Normal
4,5,21094,8920,Hemoglobin,11.46,2023-01-01,Abnormal

In [13]:
doctors.head()

,doctor_id,doctor_name,department_id,specialization,hospital_id,experience_years,doctor_grade
0,1,Dr. Sai Sharma,4,General Medicine,8,9,Consultant
1,2,Dr. Raj Nair,12,ICU,7,10,Resident
2,3,Dr. Ishaan Khan,9,Emergency,6,16,Consultant
3,4,Dr. Sai Rao,7,Gastroenterology,7,7,Consultant
4,5,Dr. Priya Menon,2,Neurology,2,12,Senior Consultant

In [14]:
followups.head()

,followup_id,admission_id,patient_id,followup_due_date,followup_completed,followup_mode,followup_outcome
0,1,1,3415,2024-03-30,Yes,OPD Visit,Stable
1,2,2,3610,2023-05-27,Yes,OPD Visit,Stable
2,3,3,7584,2025-07-02,Yes,Telemedicine,Stable
3,4,4,4459,2025-10-23,No,Call,Referred Back
4,5,5,5508,2024-05-30,Yes,Call,Stable

In [15]:
departments.head()

   department_id   department_name care_complexity
0              1        Cardiology            High
1              2         Neurology            High
2              3       Orthopedics          Medium
3              4  General Medicine          Medium
4              5       Pulmonology            High

In [16]:
doctors.head()

,doctor_id,doctor_name,department_id,specialization,hospital_id,experience_years,doctor_grade
0,1,Dr. Sai Sharma,4,General Medicine,8,9,Consultant
1,2,Dr. Raj Nair,12,ICU,7,10,Resident
2,3,Dr. Ishaan Khan,9,Emergency,6,16,Consultant
3,4,Dr. Sai Rao,7,Gastroenterology,7,7,Consultant
4,5,Dr. Priya Menon,2,Neurology,2,12,Senior Consultant

In [17]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 12090 entries, 0 to 12089
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   patient_id                 12090 non-null  int64
 1   patient_code               12090 non-null  str
 2   patient_name               12090 non-null  str
 3   age                        11879 non-null  float64
 4   gender                     12090 non-null  str
 5   city                       11920 non-null  str
 6   primary_chronic_condition  8841 non-null   str
 7   insurance_plan             12090 non-null  str
 8   income_segment             12090 non-null  str
 9   registration_date          12090 non-null  str
dtypes: float64(1), int64(1), str(8)
memory usage: 1.7 MB

In [18]:
admissions.info()

<class 'pandas.DataFrame'>
RangeIndex: 30130 entries, 0 to 30129
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   admission_id        30130 non-null  int64
 1   patient_id          30130 non-null  int64
 2   hospital_id         30130 non-null  int64
 3   department_id       30130 non-null  int64
 4   primary_doctor_id   30130 non-null  int64
 5   admission_date      30130 non-null  str
 6   discharge_date      29879 non-null  str
 7   admission_type      30130 non-null  str
 8   diagnosis           29987 non-null  str
 9   severity_level      30130 non-null  str
 10  discharge_status    30130 non-null  str
 11  readmitted_30_days  30130 non-null  str
dtypes: int64(5), str(7)
memory usage: 4.3 MB

In [19]:
treatments.info()

<class 'pandas.DataFrame'>
RangeIndex: 90160 entries, 0 to 90159
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   treatment_id      90160 non-null  int64
 1   admission_id      90160 non-null  int64
 2   doctor_id         90160 non-null  int64
 3   treatment_type    90160 non-null  str
 4   treatment_cost    89860 non-null  float64
 5   treatment_date    90160 non-null  str
 6   treatment_status  90160 non-null  str
dtypes: float64(1), int64(3), str(3)
memory usage: 7.3 MB

In [20]:
billing.info()

<class 'pandas.DataFrame'>
RangeIndex: 30080 entries, 0 to 30079
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bill_id          30080 non-null  int64
 1   admission_id     30080 non-null  int64
 2   patient_id       30080 non-null  int64
 3   payer_type       30080 non-null  str
 4   gross_amount     29960 non-null  float64
 5   discount_amount  30080 non-null  float64
 6   insurance_paid   30080 non-null  float64
 7   patient_paid     30080 non-null  float64
 8   claim_status     30080 non-null  str
 9   bill_date        30080 non-null  str
dtypes: float64(4), int64(3), str(3)
memory usage: 3.2 MB

In [21]:
pharmacy.info()

<class 'pandas.DataFrame'>
RangeIndex: 70090 entries, 0 to 70089
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       70090 non-null  int64
 1   admission_id   70090 non-null  int64
 2   patient_id     70090 non-null  int64
 3   medicine_name  70090 non-null  str
 4   quantity       70090 non-null  int64
 5   unit_price     70090 non-null  float64
 6   line_amount    69940 non-null  float64
 7   pharmacy_type  70090 non-null  str
dtypes: float64(2), int64(4), str(2)
memory usage: 5.7 MB

In [22]:
labs.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lab_id        60000 non-null  int64
 1   admission_id  60000 non-null  int64
 2   patient_id    60000 non-null  int64
 3   test_name     60000 non-null  str
 4   test_value    59880 non-null  float64
 5   test_date     60000 non-null  str
 6   result_flag   60000 non-null  str
dtypes: float64(1), int64(3), str(3)
memory usage: 4.6 MB

In [23]:
doctors.info()

<class 'pandas.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         260 non-null    int64
 1   doctor_name       260 non-null    str
 2   department_id     260 non-null    int64
 3   specialization    260 non-null    str
 4   hospital_id       260 non-null    int64
 5   experience_years  260 non-null    int64
 6   doctor_grade      260 non-null    str
dtypes: int64(4), str(3)
memory usage: 23.7 KB

In [24]:
followups.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   followup_id         30000 non-null  int64
 1   admission_id        30000 non-null  int64
 2   patient_id          30000 non-null  int64
 3   followup_due_date   30000 non-null  str
 4   followup_completed  30000 non-null  str
 5   followup_mode       30000 non-null  str
 6   followup_outcome    30000 non-null  str
dtypes: int64(3), str(4)
memory usage: 2.4 MB

In [25]:
departments.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department_id    12 non-null     int64
 1   department_name  12 non-null     str
 2   care_complexity  12 non-null     str
dtypes: int64(1), str(2)
memory usage: 611.0 bytes

In [26]:
hospitals.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hospital_id     8 non-null      int64
 1   hospital_name   8 non-null      str
 2   city            8 non-null      str
 3   ownership_type  8 non-null      str
 4   bed_capacity    8 non-null      int64
 5   launch_year     8 non-null      int64
dtypes: int64(3), str(3)
memory usage: 836.0 bytes

In [27]:
def create_quality_report(df, table_name):
    report = pd.DataFrame()
    report['table_name'] = [table_name] * len(df.columns)
    report['column_name'] = df.columns      
    report['data_type'] = df.dtypes.astype(str).values
    report['missing_count'] = df.isna().sum().values
    report['missing_percentage'] = (df.isna().mean() * 100).round(2).values
    report['unique_values'] = df.nunique(dropna=True).values
    return report

patients_quality = create_quality_report(patients, 'patients')
admissions_quality = create_quality_report(admissions, 'admissions')
treatments_quality = create_quality_report(treatments, 'treatments')
billing_quality = create_quality_report(billing, 'billing')
pharmacy_quality = create_quality_report(pharmacy,'pharmacy')
labs_quality = create_quality_report(labs,'labs')
doctors_quality = create_quality_report(doctors,'doctors')
followups_quality = create_quality_report(followups,'followups')
departments_quality = create_quality_report(departments,'departments')
hospitals_quality = create_quality_report(hospitals,'hospitals')

quality_report = pd.concat(
    [patients_quality, admissions_quality, treatments_quality,billing_quality,pharmacy_quality,labs_quality,
     doctors_quality,followups_quality,departments_quality,hospitals_quality],
    ignore_index=True
)

quality_report.sort_values('missing_percentage', ascending=False).head(n=100)

,table_name,column_name,data_type,missing_count,missing_percentage,unique_values
6,patients,primary_chronic_condition,str,3249,26.87,7
3,patients,age,float64,211,1.75,101
5,patients,city,str,170,1.41,14
16,admissions,discharge_date,str,251,0.83,1099
18,admissions,diagnosis,str,143,0.47,43
...,...,...,...,...,...,...
72,hospitals,hospital_name,str,0,0.00,8
73,hospitals,city,str,0,0.00,8
74,hospitals,ownership_type,str,0,0.00,2
75,hospitals,bed_capacity,int64,0,0.00,8
76,hospitals,launch_year,int64,0,0.00,8

## 1.clean patients dataset

In [28]:
patients_clean = patients.copy()
print('Before duplicate removal:', patients_clean.shape)
patients_clean = patients_clean.drop_duplicates()
print('After duplicate removal:', patients_clean.shape)

Before duplicate removal: (12090, 10)
After duplicate removal: (12090, 10)

In [29]:
# Convert age to numeric.
# If age contains text or invalid values, errors='coerce' converts them to NaN.
patients_clean['age_clean'] = pd.to_numeric(patients_clean['age'], errors='coerce')

# Mark impossible ages as missing.
patients_clean.loc[patients_clean['age_clean'] < 0, 'age_clean'] = np.nan
patients_clean.loc[patients_clean['age_clean'] > 110, 'age_clean'] = np.nan

# Fill missing age using median because median is less affected by outliers.
median_age = patients_clean['age_clean'].median()
patients_clean['age_clean'] = patients_clean['age_clean'].fillna(median_age)

patients_clean[['age', 'age_clean']].head()

    age  age_clean
0  46.0       46.0
1  58.0       58.0
2  51.0       51.0
3  25.0       25.0
4  54.0       54.0

In [30]:
# Standardize gender values.
patients_clean['gender_clean'] = patients_clean['gender'].astype(str).str.strip().str.lower()

patients_clean['gender_clean'] = patients_clean['gender_clean'].replace({
    'm': 'Male',
    'male': 'Male',
    'f': 'Female',
    'female': 'Female',
    'femle': 'Female',
    'other': 'Other',
    'unknown': 'Unknown',
    'nan': 'Unknown'
})

patients_clean['gender_clean'].value_counts()

gender_clean
Female     6125
Male       5769
Other       130
Unknown      66
Name: count, dtype: int64

In [31]:
patients_clean['primary_chronic_condition'].value_counts()

primary_chronic_condition
Hypertension     2387
Diabetes         2134
Asthma           1058
COPD              975
Heart Failure     937
CKD               876
Cancer            474
Name: count, dtype: int64

In [32]:
# Standardize chronic condition values.
patients_clean['chronic_condition_clean'] = (
    patients_clean['primary_chronic_condition']
    .astype(str)
    .str.strip()
    .str.title()
)

In [33]:
patients_clean['chronic_condition_clean'].value_counts()

chronic_condition_clean
Hypertension     2387
Diabetes         2134
Asthma           1058
Copd              975
Heart Failure     937
Ckd               876
Cancer            474
Name: count, dtype: int64

In [34]:
# Replace missing/blank/unwanted text with Unknown
patients_clean['chronic_condition_clean'] = patients_clean['chronic_condition_clean'].replace({
    'Nan': 'Unknown',
    '': 'Unknown',
    'None': 'Unknown',
    'Null': 'Unknown'
})

In [35]:
patients_clean['chronic_condition_clean'].value_counts()

chronic_condition_clean
Hypertension     2387
Diabetes         2134
Asthma           1058
Copd              975
Heart Failure     937
Ckd               876
Cancer            474
Name: count, dtype: int64

In [36]:
patients_clean['chronic_condition_clean']=patients_clean['chronic_condition_clean'].fillna("Unknown")

In [37]:
patients_clean['chronic_condition_clean'].value_counts()

chronic_condition_clean
Unknown          3249
Hypertension     2387
Diabetes         2134
Asthma           1058
Copd              975
Heart Failure     937
Ckd               876
Cancer            474
Name: count, dtype: int64

In [38]:
# Create chronic flag
# If chronic condition is available, flag = 1
# If missing/unknown, flag = 0
patients_clean['chronic_flag'] = patients_clean['chronic_condition_clean'].apply(
    lambda x: 0 if x == 'Unknown' else 1
)

patients_clean[['primary_chronic_condition', 'chronic_condition_clean', 'chronic_flag']].head()

  primary_chronic_condition chronic_condition_clean  chronic_flag
0             Heart Failure           Heart Failure             1
1             Heart Failure           Heart Failure             1
2              Hypertension            Hypertension             1
3             Heart Failure           Heart Failure             1
4                    Asthma                  Asthma             1

In [39]:
patients_clean['chronic_flag'].value_counts()

chronic_flag
1    8841
0    3249
Name: count, dtype: int64

## 2.clean admission dataset

In [40]:
admissions_clean = admissions.copy()

admissions_clean = admissions_clean.drop_duplicates()

In [41]:
len(admissions)

30130

In [42]:
len(admissions_clean)

30000

In [43]:
admissions_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   admission_id        30000 non-null  int64
 1   patient_id          30000 non-null  int64
 2   hospital_id         30000 non-null  int64
 3   department_id       30000 non-null  int64
 4   primary_doctor_id   30000 non-null  int64
 5   admission_date      30000 non-null  str
 6   discharge_date      29750 non-null  str
 7   admission_type      30000 non-null  str
 8   diagnosis           29860 non-null  str
 9   severity_level      30000 non-null  str
 10  discharge_status    30000 non-null  str
 11  readmitted_30_days  30000 non-null  str
dtypes: int64(5), str(7)
memory usage: 4.3 MB

In [44]:
# changing the data type of the date realted columns
admissions_clean['admission_date'] = pd.to_datetime(admissions_clean['admission_date'], errors='coerce')
admissions_clean['discharge_date'] = pd.to_datetime(admissions_clean['discharge_date'], errors='coerce')

In [45]:
admissions_clean['length_of_stay'] = (
    admissions_clean['discharge_date'] - admissions_clean['admission_date']
).dt.days

admissions_clean[['admission_date', 'discharge_date', 'length_of_stay']].head()

  admission_date discharge_date  length_of_stay
0     2024-03-10     2024-03-16             6.0
1     2023-05-19     2023-05-20             1.0
2     2025-06-16     2025-06-18             2.0
3     2025-10-15     2025-10-16             1.0
4     2024-05-07     2024-05-23            16.0

In [46]:
admissions_clean['discharge_date'].isnull().sum()

np.int64(250)

In [47]:
admissions_clean[admissions_clean['discharge_date'].isnull()]

,admission_id,patient_id,hospital_id,department_id,primary_doctor_id,admission_date,discharge_date,admission_type,diagnosis,severity_level,discharge_status,readmitted_30_days,length_of_stay
7,8,1969,4,2,67,2025-09-30,NaT,Follow-up,Seizure Disorder,High,LAMA,No,NaN
24,25,1965,6,3,106,2024-04-09,NaT,Emergency,Joint Replacement,Moderate,Home,Yes,NaN
267,268,605,7,5,247,2023-02-16,NaT,Emergency,COPD Exacerbation,Moderate,Home,Yes,NaN
343,344,589,5,5,247,2023-06-14,NaT,Referral,Asthma Attack,High,Home,Yes,NaN
409,410,1884,4,12,35,2025-06-03,NaT,Emergency,Respiratory Failure,Moderate,Transferred,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29647,29648,2834,2,4,224,2025-10-25,NaT,Emergency,Fever Under Evaluation,Low,Home,Yes,NaN
29669,29670,11698,5,9,3,2023-08-30,NaT,Referral,Trauma,Moderate,Transferred,Yes,NaN
29916,29917,905,5,9,221,2024-09-26,NaT,Referral,Trauma,Moderate,Home,No,NaN
29951,29952,586,7,6,18,2023-12-25,NaT,Emergency,CKD Complication,Low,Home,No,NaN
29971,29972,11936,8,1,172,2025-06-28,NaT,Referral,Acute Coronary Syndrome,Moderate,Home,Yes,NaN

In [48]:
# Handle wrong length of stay values.
# Negative stay means discharge happened before admission, which is impossible.
admissions_clean.loc[admissions_clean['length_of_stay'] < 0, 'length_of_stay'] = np.nan

In [49]:
# Fill missing length of stay using median length of stay.
median_los = admissions_clean['length_of_stay'].median()
admissions_clean['length_of_stay'] = admissions_clean['length_of_stay'].fillna(median_los)

admissions_clean['length_of_stay'].describe()

count    30000.000000
mean         5.915333
std          5.432054
min          1.000000
25%          2.000000
50%          4.000000
75%          8.000000
max         66.000000
Name: length_of_stay, dtype: float64

In [50]:
admissions_clean.head()

,admission_id,patient_id,hospital_id,department_id,primary_doctor_id,admission_date,discharge_date,admission_type,diagnosis,severity_level,discharge_status,readmitted_30_days,length_of_stay
0,1,3415,8,4,123,2024-03-10,2024-03-16,Emergency,Anemia,Critical,Home,Yes,6.0
1,2,3610,8,1,209,2023-05-19,2023-05-20,Planned,Arrhythmia,Moderate,Home,No,1.0
2,3,7584,8,3,190,2025-06-16,2025-06-18,Emergency,Joint Replacement,Moderate,Home,Yes,2.0
3,4,4459,2,3,176,2025-10-15,2025-10-16,Referral,Joint Replacement,Moderate,Home,No,1.0
4,5,5508,3,12,140,2024-05-07,2024-05-23,Planned,Multi Organ Dysfunction,Moderate,Home,No,16.0

In [51]:
admissions_clean['readmitted_30_days'].unique()

<ArrowStringArray>
['Yes', 'No', 'Y', 'FALSE', 'yes', 'TRUE', 'N', 'no']
Length: 8, dtype: str

In [52]:
# Standardize readmission labels into 1 and 0.
admissions_clean['readmitted_clean'] = admissions_clean['readmitted_30_days'].astype(str).str.strip().str.lower()

admissions_clean['readmitted_flag'] = admissions_clean['readmitted_clean'].replace({
    'yes': 1,
    'y': 1,
    'true': 1,
    'no': 0,
    'n': 0,
    'false': 0,
    'nan': 0
}).astype(int)

admissions_clean['readmitted_flag'].value_counts(normalize=True) * 100

readmitted_flag
0    51.53
1    48.47
Name: proportion, dtype: float64

## 3.clean treatement cost data set

In [53]:
treatments_clean = treatments.copy()

treatments_clean['treatment_cost'] = pd.to_numeric(
    treatments_clean['treatment_cost'],
    errors='coerce'
)

treatments_clean['cost_outlier_flag'] = 0

In [54]:
treatments.duplicated().sum()

np.int64(160)

In [55]:
print('Before duplicate removal:', treatments_clean.shape)
treatments_clean = treatments_clean.drop_duplicates()
print('After duplicate removal:', treatments_clean.shape)

Before duplicate removal: (90160, 8)
After duplicate removal: (90000, 8)

In [56]:
treatments_clean.head()

,treatment_id,admission_id,doctor_id,treatment_type,treatment_cost,treatment_date,treatment_status,cost_outlier_flag
0,1,27337,62,Surgery,52636.30,2023-01-01,Completed,0
1,2,982,242,Imaging,7478.12,2023-01-01,Completed,0
2,3,17082,238,Chemotherapy,27451.58,2023-01-01,Completed,0
3,4,4096,1,Lab Package,3379.43,2023-01-01,Pending,0
4,5,26108,227,ICU Care,19993.51,2023-01-01,Completed,0

In [57]:
treatments_clean['cost_outlier_flag'].unique()

array([0])

In [58]:


treatments_clean.loc[
    (treatments_clean['treatment_cost'] < 0) | (treatments_clean['treatment_cost'] > 500000),
    'cost_outlier_flag'
] = 1

print('Number of cost outliers:', treatments_clean['cost_outlier_flag'].sum())

Number of cost outliers: 212

In [59]:
# Convert impossible treatment cost into missing value.
treatments_clean.loc[
    treatments_clean['cost_outlier_flag'] == 1,
    'treatment_cost'
] = np.nan

In [60]:
treatments_clean.head()

,treatment_id,admission_id,doctor_id,treatment_type,treatment_cost,treatment_date,treatment_status,cost_outlier_flag
0,1,27337,62,Surgery,52636.30,2023-01-01,Completed,0
1,2,982,242,Imaging,7478.12,2023-01-01,Completed,0
2,3,17082,238,Chemotherapy,27451.58,2023-01-01,Completed,0
3,4,4096,1,Lab Package,3379.43,2023-01-01,Pending,0
4,5,26108,227,ICU Care,19993.51,2023-01-01,Completed,0

In [61]:
# Fill missing treatment cost using median cost of the same treatment type.
treatments_clean['treatment_cost_clean'] = treatments_clean.groupby('treatment_type')['treatment_cost'].transform(
    lambda values: values.fillna(values.median())
)

treatments_clean[['treatment_type', 'treatment_cost', 'treatment_cost_clean', 'cost_outlier_flag']].head()

  treatment_type  treatment_cost  treatment_cost_clean  cost_outlier_flag
0        Surgery        52636.30              52636.30                  0
1        Imaging         7478.12               7478.12                  0
2   Chemotherapy        27451.58              27451.58                  0
3    Lab Package         3379.43               3379.43                  0
4       ICU Care        19993.51              19993.51                  0

## 4.clean Billing data set

In [62]:
billing_clean = billing.copy()

In [63]:
billing.duplicated().sum()

np.int64(80)

In [64]:
print('Before duplicate removal:', billing_clean.shape)
billing_clean = billing_clean.drop_duplicates()
print('After duplicate removal:', billing_clean.shape)

Before duplicate removal: (30080, 10)
After duplicate removal: (30000, 10)

In [65]:
billing_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bill_id          30000 non-null  int64
 1   admission_id     30000 non-null  int64
 2   patient_id       30000 non-null  int64
 3   payer_type       30000 non-null  str
 4   gross_amount     29880 non-null  float64
 5   discount_amount  30000 non-null  float64
 6   insurance_paid   30000 non-null  float64
 7   patient_paid     30000 non-null  float64
 8   claim_status     30000 non-null  str
 9   bill_date        30000 non-null  str
dtypes: float64(4), int64(3), str(3)
memory usage: 3.2 MB

In [66]:
billing_clean.head()

,bill_id,admission_id,patient_id,payer_type,gross_amount,discount_amount,insurance_paid,patient_paid,claim_status,bill_date
0,1,1,3415,Premium Insurance,19940.46,1785.84,15939.06,2215.56,Paid,2024-03-10
1,2,2,3610,Basic Insurance,19034.64,558.14,13981.49,4495.01,Partial,2023-05-19
2,3,3,7584,Self Pay,20965.03,2413.86,18595.28,0.00,Rejected,2025-06-16
3,4,4,4459,Corporate Insurance,16637.20,1938.84,13657.64,1040.72,Rejected,2025-10-15
4,5,5,5508,Government Scheme,77727.52,2213.24,35959.21,39555.07,Paid,2024-05-07

In [67]:
billing_clean['gross_amount'] = (
    billing_clean['gross_amount']
    .fillna(billing_clean['gross_amount'].median())
)

In [68]:
billing_clean['bill_date'] = pd.to_datetime(billing_clean['bill_date'], errors='coerce')

In [69]:
billing_clean['bill_date'].dtype

dtype('<M8[us]')

In [70]:
billing_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bill_id          30000 non-null  int64
 1   admission_id     30000 non-null  int64
 2   patient_id       30000 non-null  int64
 3   payer_type       30000 non-null  str
 4   gross_amount     30000 non-null  float64
 5   discount_amount  30000 non-null  float64
 6   insurance_paid   30000 non-null  float64
 7   patient_paid     30000 non-null  float64
 8   claim_status     30000 non-null  str
 9   bill_date        30000 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(3), str(2)
memory usage: 2.9 MB

In [71]:
billing_clean['claim_status'].value_counts()

claim_status
Paid            19141
Partial          5606
Under Review     2997
Rejected         2139
paid               35
under_review       31
Rejected           28
PAID               23
Name: count, dtype: int64

In [72]:
billing_clean['claim_status'] = billing_clean['claim_status'].astype(str).str.strip().str.lower()

billing_clean['claim_status'] = billing_clean['claim_status'].replace({
    'paid': 'Paid',
    'Paid': 'Paid',
    'PAID': 'Paid',
    'Under Review': 'Under_review',
    'under_review': 'Under_review',
     'under review': 'Under_review',
    'rejected': 'Rejected',
    'partial':'Partial'
    
})

billing_clean['claim_status'].value_counts()

claim_status
Paid            19199
Partial          5606
Under_review     3028
Rejected         2167
Name: count, dtype: int64

## 5.clean pharmacy dataset

In [73]:
pharmacy_clean=pharmacy.copy()

In [74]:
pharmacy.duplicated().sum()

np.int64(90)

In [75]:
print('Before duplicate removal:', pharmacy_clean.shape)
pharmacy_clean = pharmacy_clean.drop_duplicates()
print('After duplicate removal:', pharmacy_clean.shape)

Before duplicate removal: (70090, 8)
After duplicate removal: (70000, 8)

In [76]:
pharmacy_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       70000 non-null  int64
 1   admission_id   70000 non-null  int64
 2   patient_id     70000 non-null  int64
 3   medicine_name  70000 non-null  str
 4   quantity       70000 non-null  int64
 5   unit_price     70000 non-null  float64
 6   line_amount    69850 non-null  float64
 7   pharmacy_type  70000 non-null  str
dtypes: float64(2), int64(4), str(2)
memory usage: 5.7 MB

In [77]:
pharmacy_clean.head()

,order_id,admission_id,patient_id,medicine_name,quantity,unit_price,line_amount,pharmacy_type
0,1,29377,7899,Insulin,15,57.66,864.90,IP Pharmacy
1,2,25956,2404,Anticoagulant,1,33.52,33.52,IP Pharmacy
2,3,18883,6450,Chemotherapy Drug,17,188.65,3207.07,OP Pharmacy
3,4,21967,10792,Metformin,3,37.73,113.18,OP Pharmacy
4,5,17705,4645,Amlodipine,20,95.68,1913.64,OP Pharmacy

In [78]:
pharmacy_clean['line_amount'].isnull().sum()

np.int64(150)

In [79]:
pharmacy_clean['line_amount_clean']=pharmacy_clean['line_amount'].fillna(
    (pharmacy_clean['quantity'] * pharmacy_clean['unit_price']).round(2)
)

In [80]:
pharmacy_clean['pharmacy_type'].value_counts()

pharmacy_type
IP Pharmacy    56123
OP Pharmacy    13877
Name: count, dtype: int64

In [81]:
pharmacy_clean.head()

,order_id,admission_id,patient_id,medicine_name,quantity,unit_price,line_amount,pharmacy_type,line_amount_clean
0,1,29377,7899,Insulin,15,57.66,864.90,IP Pharmacy,864.90
1,2,25956,2404,Anticoagulant,1,33.52,33.52,IP Pharmacy,33.52
2,3,18883,6450,Chemotherapy Drug,17,188.65,3207.07,OP Pharmacy,3207.07
3,4,21967,10792,Metformin,3,37.73,113.18,OP Pharmacy,113.18
4,5,17705,4645,Amlodipine,20,95.68,1913.64,OP Pharmacy,1913.64

## 6.clean labs dataset

In [82]:
labs_clean=labs.copy()

In [83]:
labs.duplicated().sum()

np.int64(0)

In [84]:
labs_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lab_id        60000 non-null  int64
 1   admission_id  60000 non-null  int64
 2   patient_id    60000 non-null  int64
 3   test_name     60000 non-null  str
 4   test_value    59880 non-null  float64
 5   test_date     60000 non-null  str
 6   result_flag   60000 non-null  str
dtypes: float64(1), int64(3), str(3)
memory usage: 4.6 MB

In [85]:
labs_clean.head()

,lab_id,admission_id,patient_id,test_name,test_value,test_date,result_flag
0,1,2133,11981,CRP,5.99,2023-01-01,Abnormal
1,2,5569,5064,Sodium,2.46,2023-01-01,Normal
2,3,17271,1824,CRP,2.84,2023-01-01,Abnormal
3,4,24486,9939,HbA1c,14.91,2023-01-01,Normal
4,5,21094,8920,Hemoglobin,11.46,2023-01-01,Abnormal

In [86]:
labs_clean['test_name'].value_counts()

test_name
CRP           7597
Hemoglobin    7535
Sodium        7528
WBC           7503
Troponin      7482
Potassium     7477
Creatinine    7468
HbA1c         7410
Name: count, dtype: int64

In [87]:
labs_clean['test_value'].isnull().sum()

np.int64(120)

In [88]:
labs_clean['test_value_clean']=labs_clean.groupby('test_name')['test_value'].transform(
    lambda values:values.fillna(values.median()))

In [89]:
labs_clean['result_flag'].unique()

<ArrowStringArray>
['Abnormal', 'Normal', 'Critical']
Length: 3, dtype: str

In [90]:
labs_clean['test_date'] = pd.to_datetime(labs_clean['test_date'], errors='coerce')

In [91]:
labs_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   lab_id            60000 non-null  int64
 1   admission_id      60000 non-null  int64
 2   patient_id        60000 non-null  int64
 3   test_name         60000 non-null  str
 4   test_value        59880 non-null  float64
 5   test_date         60000 non-null  datetime64[us]
 6   result_flag       60000 non-null  str
 7   test_value_clean  60000 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(3), str(2)
memory usage: 4.4 MB

## 7.clean doctors dataset

In [92]:
doctors_clean=doctors.copy()

In [93]:
doctors.duplicated().sum()

np.int64(0)

In [94]:
doctors_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         260 non-null    int64
 1   doctor_name       260 non-null    str
 2   department_id     260 non-null    int64
 3   specialization    260 non-null    str
 4   hospital_id       260 non-null    int64
 5   experience_years  260 non-null    int64
 6   doctor_grade      260 non-null    str
dtypes: int64(4), str(3)
memory usage: 23.7 KB

In [95]:
doctors_clean.head()

,doctor_id,doctor_name,department_id,specialization,hospital_id,experience_years,doctor_grade
0,1,Dr. Sai Sharma,4,General Medicine,8,9,Consultant
1,2,Dr. Raj Nair,12,ICU,7,10,Resident
2,3,Dr. Ishaan Khan,9,Emergency,6,16,Consultant
3,4,Dr. Sai Rao,7,Gastroenterology,7,7,Consultant
4,5,Dr. Priya Menon,2,Neurology,2,12,Senior Consultant

## 8.clean followups dataset

In [96]:
followups_clean=followups.copy()

In [97]:
followups.duplicated().sum()

np.int64(0)

In [98]:
followups_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   followup_id         30000 non-null  int64
 1   admission_id        30000 non-null  int64
 2   patient_id          30000 non-null  int64
 3   followup_due_date   30000 non-null  str
 4   followup_completed  30000 non-null  str
 5   followup_mode       30000 non-null  str
 6   followup_outcome    30000 non-null  str
dtypes: int64(3), str(4)
memory usage: 2.4 MB

In [99]:
followups_clean.head()

,followup_id,admission_id,patient_id,followup_due_date,followup_completed,followup_mode,followup_outcome
0,1,1,3415,2024-03-30,Yes,OPD Visit,Stable
1,2,2,3610,2023-05-27,Yes,OPD Visit,Stable
2,3,3,7584,2025-07-02,Yes,Telemedicine,Stable
3,4,4,4459,2025-10-23,No,Call,Referred Back
4,5,5,5508,2024-05-30,Yes,Call,Stable

In [100]:
followups_clean['followup_due_date'] = pd.to_datetime(followups_clean['followup_due_date'], errors='coerce')

In [101]:
followups_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   followup_id         30000 non-null  int64
 1   admission_id        30000 non-null  int64
 2   patient_id          30000 non-null  int64
 3   followup_due_date   30000 non-null  datetime64[us]
 4   followup_completed  30000 non-null  str
 5   followup_mode       30000 non-null  str
 6   followup_outcome    30000 non-null  str
dtypes: datetime64[us](1), int64(3), str(3)
memory usage: 2.2 MB

## 9.clean departments dataset

In [102]:
departments_clean=departments.copy()

In [103]:
departments.duplicated().sum()

np.int64(0)

In [104]:
departments_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department_id    12 non-null     int64
 1   department_name  12 non-null     str
 2   care_complexity  12 non-null     str
dtypes: int64(1), str(2)
memory usage: 611.0 bytes

In [105]:
departments_clean.head()

   department_id   department_name care_complexity
0              1        Cardiology            High
1              2         Neurology            High
2              3       Orthopedics          Medium
3              4  General Medicine          Medium
4              5       Pulmonology            High

In [106]:
departments_clean['care_complexity'].unique()

<ArrowStringArray>
['High', 'Medium', 'Very High', 'Low']
Length: 4, dtype: str

In [107]:
departments_clean['care_complexity'].value_counts()

care_complexity
High         5
Medium       4
Very High    2
Low          1
Name: count, dtype: int64

## 10. clean hospitals dataset

In [108]:
hospitals_clean=hospitals.copy()

In [109]:
hospitals_clean.duplicated().sum()

np.int64(0)

In [110]:
hospitals_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hospital_id     8 non-null      int64
 1   hospital_name   8 non-null      str
 2   city            8 non-null      str
 3   ownership_type  8 non-null      str
 4   bed_capacity    8 non-null      int64
 5   launch_year     8 non-null      int64
dtypes: int64(3), str(3)
memory usage: 836.0 bytes

In [111]:
hospitals_clean.head()

,hospital_id,hospital_name,city,ownership_type,bed_capacity,launch_year
0,1,MedNova Hospital - Hyderabad,Hyderabad,Private,420,2009
1,2,MedNova Hospital - Bengaluru,Bengaluru,Private,360,2012
2,3,MedNova Hospital - Chennai,Chennai,Trust,310,2014
3,4,MedNova Hospital - Pune,Pune,Private,280,2018
4,5,MedNova Hospital - Mumbai,Mumbai,Private,390,2011

In [113]:
patients_clean.to_csv("patients_clean.csv", index=False)
admissions_clean.to_csv("admissions_clean.csv", index=False)
billing_clean.to_csv("billing_clean.csv", index=False)
treatments_clean.to_csv("treatments_clean.csv", index=False)
labs_clean.to_csv("labs_clean.csv", index=False)
pharmacy_clean.to_csv("pharmacy_clean.csv", index=False)
doctors_clean.to_csv("doctors_clean.csv", index=False)
followups_clean.to_csv("followups_clean.csv", index=False)
departments_clean.to_csv("departments_clean.csv", index=False)
hospitals_clean.to_csv("hospitals_clean.csv", index=False)